import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "../components/Icons";
import HireMe from "../components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
	return (
		<>
			<Head>
				<title>Rashad | Portfolio </title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="flex items-center w-full min-h-screen text-dark dark:text-light ">
				<Layout className="pt-0">
					<div className="flex items-center justify-between w-full">
						<div className="w-1/2">
							<Image
								src={profilePic}
								alt=""
								className="w-full h-auto"
								priority
								sizes="(max-width:768px) 100vw , (max-width:1200px) 50vw,50vw"
							/>
						</div>
						<div className="flex flex-col items-center self-center w-1/2">
							<AnimatedText
								text="Turning Vision Into Reality With Code And Design"
								className="!text-6xl !text-left"
							/>
							<p className="my-4 text-base font-medium ">
								As a skilled full-stack developer, I am dedicated to turning
								ideas into innovative web applications. Explore my latest
								projects and articles, showcasing my expertise in React.js and
								web development
							</p>
							<div className="flex items-center self-start mt-2">
								<Link
									href="/dummy.pdf"
									target={"_blank"}
									className="flex items-center bg-dark
								 text-light p-2.5 px-6 rounded-lg text-lg font-semibold
								  hover:bg-light hover:text-dark border-2 border-solid 
								  border-transparent hover:border-dark
								  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
								  "
									download={true}
								>
									Resume
									<LinkArrow className={"w-6 ml-1"} />
								</Link>
								<Link
									href="mailto:akyrashad@gmail.com"
									target={"_blank"}
									className="flex items-center ml-4  text-lg dark:text-light  px-5 py-2.5  mr-2 mb-2 font-medium text-center underline capitalize rounded-lg shadow-lg text-dark bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80"
								>
									Contact
								</Link>
							</div>
						</div>
					</div>
				</Layout>
				<HireMe />
				<div className="absolute right-8 bottom-8 inline-block w-24">
					<Image src={lightBulb} alt={"Rashad"} className="w-full h-auto" />
				</div>
			</main>
			<about />
		</>
	);
}
// CircularText2
